name: Metrics
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: Da-Zhao1997
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Shanghai # replace with your timezone
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
      - name: Full-year calendar
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics/isocalendar.fullyear.svg
          token: ${{ secrets.METRICS_TOKEN }}
          # 不添加基础信息
          base: ""
          # 使用此插件
          plugin_isocalendar: yes
          # 设置成显示整年
          plugin_isocalendar_duration: full-year
